# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2e2f7fda1adcf7bfeb6d28a8f1743e6e"
name = "Dynamic Delivery Scheduler"
handle = "dynamic-delivery-scheduler-1"
application_url = "https://told-apnic-composite-southeast.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "sagar-devstore.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders, write_orders, read_products, write_products, read_shipping, write_shipping,read_delivery_customizations,write_delivery_customizations"

[auth]
redirect_urls = [
  "https://told-apnic-composite-southeast.trycloudflare.com/auth/callback",
  "https://told-apnic-composite-southeast.trycloudflare.com/auth/shopify/callback",
  "https://told-apnic-composite-southeast.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
